openapi: 3.0.2

info:
  title: TODO API
  description: |-
    This API is a backend for the TODO example
  version: 0.1.0

paths:
  /todo-items:
    get:
      operationId: list-todo-items
      description: Lists all TODO items
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/todo-item"

    post:
      operationId: add-todo-item
      description: Add a todo-item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/todo-item-create"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/todo-item"

  /todo-items/{id}:
    put:
      operationId: modify-todo-item
      description: Modify existing todo-item or mark as done
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the todo item
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/todo-item-update"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/todo-item"

    delete:
      operationId: delete-todo-item
      description: Delete an existing todo item
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the todo item
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: No Content

  /todo-items/{id}/done:
    post:
      operationId: todo-item-set-done
      description: >
        Mark todo item as done
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the todo item
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/todo-item"

components:
  schemas:
    todo-item:
      type: object
      required:
        - id
        - description
        - done
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        description:
          type: string
          minLength: 1
        done:
          type: boolean

    todo-item-create:
      type: object
      required:
        - description
      properties:
        description:
          type: string
          minLength: 1

    todo-item-update:
      type: object
      required:
        - description
      properties:
        description:
          type: string
          minLength: 1
